#!/bin/sh

echo "LEXING ALL TRAINING DATA"
cd lib/pyli/
for f in ../../data/train/*.py
do
    BN=`basename ${f%\.*}`.lx
    cat $f | make -s pyle > ../../data/lexed/$BN 2> /dev/null
    echo ../data/lexed/$BN
done
cd ../../
